name: 'Dependency Review'
on: 
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9b0655f430fba8c7001d4e38f8d4306db5c6e0ab # v1
        with:
          egress-policy: block
          disable-telemetry: true
          allowed-endpoints: >
            api.github.com:443
            github.com:443

      - name: 'Checkout Repository'
        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
        
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@3f943b86c9a289f4e632c632695e2e0898d9d67d
